# Generated by Django 3.0.2 on 2020-05-22 15:23

from django.db import migrations, models
import django.db.models.deletion
import tools.random


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('number', models.FloatField(verbose_name='交易的数量总量')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '可预定'), (1, '待付款'), (2, '已付款'), (3, '完成'), (4, '取消'), (5, '删除')], default=0, help_text='状态', verbose_name='状态')),
                ('serial_no', models.CharField(default=tools.random.buy_code, max_length=50, unique=True)),
                ('price', models.PositiveIntegerField(default=0, help_text='收购单价', verbose_name='buy_price')),
            ],
            options={
                'verbose_name': '收购表',
                'verbose_name_plural': '收购表',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BuyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('img', models.ImageField(default=None, help_text='图片', null=True, upload_to='buy/order/detail/')),
            ],
            options={
                'verbose_name': '收购完善的信息',
                'verbose_name_plural': '收购完善的信息',
            },
        ),
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待支付'), (1, '已支付'), (3, '取消'), (2, '已完成')], default=0, verbose_name='状态')),
                ('serial_no', models.CharField(default=tools.random.buy_record_code, max_length=50)),
            ],
            options={
                'verbose_name': '出售购买记录',
                'verbose_name_plural': '出售购买记录',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('count', models.IntegerField(help_text='发布的数量', verbose_name='数量')),
                ('status', models.IntegerField(help_text='当前状态', verbose_name='状态')),
                ('flag', models.BooleanField(help_text='是否是出售订单, yes 为出售订单， no为收购订单', verbose_name='类型')),
                ('price', models.FloatField(help_text='标记价格', verbose_name='价格')),
                ('serial', models.CharField(default=tools.random.deal_code, help_text='订单号, 自动生成', max_length=50, verbose_name='订单号')),
            ],
            options={
                'verbose_name': '交易',
                'verbose_name_plural': '交易',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('flag', models.BooleanField(default=False, help_text='标记', verbose_name='标记')),
                ('serial', models.CharField(default=tools.random.deal_code, help_text='订单号, 自动生成', max_length=50, verbose_name='订单号')),
                ('status', models.PositiveSmallIntegerField(help_text='状态', verbose_name='状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('number', models.FloatField(verbose_name='交易的数量总量')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '可预定'), (1, '待付款'), (2, '已付款'), (3, '完成'), (4, '取消'), (5, '删除')], default=0, help_text='状态', verbose_name='状态')),
                ('serial_no', models.CharField(default=tools.random.sell_code, max_length=50, unique=True)),
                ('price', models.PositiveIntegerField(default=0, help_text='出售单价', verbose_name='sell_price')),
            ],
            options={
                'verbose_name': '出售表',
                'verbose_name_plural': '出售表',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('img', models.ImageField(default=None, help_text='图片', upload_to='sell/order/detail/')),
            ],
            options={
                'verbose_name': '出售完善的信息',
                'verbose_name_plural': '出售完善的信息',
            },
        ),
        migrations.CreateModel(
            name='TPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('price', models.FloatField(default=0.03, help_text='参考价格 手动填写', verbose_name='价格')),
                ('t_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '当日参考价格',
                'verbose_name_plural': '当日参考价格',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('price', models.FloatField(default=0, help_text='单价', verbose_name='price')),
                ('count', models.FloatField(default=0, help_text='数量', verbose_name='count')),
                ('total', models.FloatField(default=0, help_text='总价', verbose_name='total_price')),
            ],
            options={
                'verbose_name': '成交的交易记录',
                'verbose_name_plural': '成交的交易记录',
            },
        ),
        migrations.CreateModel(
            name='SellRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '已付款'), (3, '取消'), (2, '已完成')], default=0, verbose_name='状态')),
                ('serial_no', models.CharField(default=tools.random.sell_record_code, max_length=50)),
                ('sell', models.ForeignKey(help_text='相关订单', on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='trade.Sell', verbose_name='sell')),
            ],
            options={
                'verbose_name': '出售记录',
                'verbose_name_plural': '出售记录',
            },
        ),
    ]
