# Generated by Django 3.0.2 on 2020-05-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrecord',
            name='user',
            field=models.ForeignKey(help_text='出售者', on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='record',
            field=models.ForeignKey(help_text='出售记录', on_delete=django.db.models.deletion.CASCADE, to='trade.SellRecord', verbose_name='record_id'),
        ),
        migrations.AddField(
            model_name='sell',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='deal',
            field=models.ForeignKey(help_text='有关的发布信息', on_delete=django.db.models.deletion.DO_NOTHING, to='trade.Deal', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='下单者', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='下单者'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(help_text='发布者', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='buyrecord',
            name='buy',
            field=models.ForeignKey(help_text='相关订单', on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='trade.Buy', verbose_name='buy'),
        ),
        migrations.AddField(
            model_name='buyrecord',
            name='user',
            field=models.ForeignKey(help_text='出售者', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
        migrations.AddField(
            model_name='buydetail',
            name='record',
            field=models.OneToOneField(help_text='出售记录', on_delete=django.db.models.deletion.CASCADE, to='trade.BuyRecord', verbose_name='record_id'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
