# Generated by Django 3.0.2 on 2020-05-22 15:23

from django.db import migrations, models
import django.db.models.deletion
import tools.random


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('content', models.CharField(max_length=100)),
                ('wechat', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '客服联系方式',
                'verbose_name_plural': '客服联系方式',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=20, unique=True, verbose_name='标题')),
                ('days', models.PositiveSmallIntegerField(default=30, help_text='需要的天数', verbose_name='天数')),
                ('number', models.FloatField(default=0, help_text='产出的数量', verbose_name='产出')),
                ('append', models.PositiveIntegerField(default=0, help_text='每次购买需要增加的天数 但是总产出不变', verbose_name='days_append')),
                ('cost', models.FloatField(default=0, help_text='需要的花费', verbose_name='花费')),
                ('s_no', models.CharField(default=tools.random.machine_code, max_length=100)),
                ('max_count', models.PositiveSmallIntegerField(default=0, help_text='0为不限制数量', verbose_name='限制数量')),
                ('given', models.BooleanField(default=False, help_text='是否是赠送项', verbose_name='赠送')),
            ],
            options={
                'verbose_name': '矿机表',
                'verbose_name_plural': '矿机表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('days', models.IntegerField(default=0, verbose_name='天数')),
                ('number', models.FloatField(default=0, verbose_name='days_earn')),
                ('expired', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='machine.Machine')),
            ],
            options={
                'verbose_name': '矿机租赁列表',
                'verbose_name_plural': '矿机租赁列表',
            },
        ),
    ]
