# Generated by Django 3.0.2 on 2020-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('sign', '注册'), ('news', '阅读新闻'), ('machine', '机器'), ('trade', '交易'), ('advert', '发布广告'), ('personal_information', '个人信息认证')], help_text='奖励的key 根据key进行搜索是否有存在', max_length=50, unique=True, verbose_name='奖励的key')),
                ('coin', models.FloatField(help_text='奖励或者需要扣除', verbose_name='奖励的分数')),
                ('percent', models.FloatField(default=0.0, help_text='必须用来购物的百分比', verbose_name='必须用来购物的部分')),
                ('type', models.IntegerField(help_text='奖励的类型', verbose_name='奖励的类型')),
                ('freq', models.IntegerField(choices=[(0, '有限次数'), (1, '每天次数'), (2, '每月的次数'), (3, '每年的次数'), (4, '未限制次数')], default=0, help_text='频率', verbose_name='频率')),
                ('freq_num', models.IntegerField(default=1, help_text='次数', verbose_name='次数')),
                ('desc', models.CharField(help_text='奖励的描述', max_length=30, verbose_name='奖励的描述')),
            ],
            options={
                'verbose_name': '奖励类型',
                'verbose_name_plural': '奖励类型',
            },
        ),
        migrations.CreateModel(
            name='CoinRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='规则', max_length=20, verbose_name='规则名')),
                ('min_num', models.FloatField(default=0, verbose_name='剩余的最小值')),
                ('tax', models.FloatField(default=0.25, help_text='手续费 百分比', verbose_name='出售的税')),
                ('pay', models.BooleanField(default=0, help_text='是否需要支付金额, 手动去控制', verbose_name='是否需要支付')),
                ('shop', models.FloatField(default=0.15, help_text='获取的币 多少需要进行购物, 最大是1最小是0', verbose_name='获取币的购物百分比')),
                ('advert', models.FloatField(default=1.0, help_text='发布需要消耗', verbose_name='发布消耗')),
                ('used', models.BooleanField(default=False, verbose_name='是否已经启用')),
            ],
            options={
                'verbose_name': '规则表',
                'verbose_name_plural': '规则表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('point', models.FloatField(verbose_name='获取的数量')),
                ('shop', models.FloatField(default=0, verbose_name='必须用来购物的部分，系统获得')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(default='', help_text='说明', max_length=120, verbose_name='说明')),
            ],
            options={
                'verbose_name': '货币获取的记录',
                'verbose_name_plural': '货币获取的记录',
            },
        ),
    ]
